#!/usr/bin/env bash
# Extract clang AST (with macro expansion) for a C++ feature project.
#
# Usage: extract.sh <cpp-dir>
#   <cpp-dir>  Directory containing the C++ project (with *.h / *.cpp).
#
# Output: <cpp-dir>/../ast/{preprocessed.cpp, ast.json}
#
# Requires: clang++ >= 10
set -euo pipefail

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <cpp-dir>" >&2
    exit 1
fi

CPP_DIR="$(cd "$1" && pwd)"
AST_DIR="$(cd "$CPP_DIR/.." && pwd)/ast"
mkdir -p "$AST_DIR"

# Collect public headers (*.h, *.hpp) — these define the API surface we want to inspect.
HEADERS=( $(find "$CPP_DIR" -maxdepth 2 -type f \( -name '*.h' -o -name '*.hpp' \) | sort) )
if [ "${#HEADERS[@]}" -eq 0 ]; then
    echo "error: no headers found in $CPP_DIR" >&2
    exit 2
fi

# Synthetic TU that includes every header.
TMP_TU="$AST_DIR/_all_headers.cpp"
{
    echo "// Auto-generated by extract.sh — combines all headers for AST analysis."
    for h in "${HEADERS[@]}"; do
        echo "#include \"$h\""
    done
} > "$TMP_TU"

CXX=${CXX:-clang++}
STD=${CXX_STD:-c++17}

echo "[ast] macro-expanding with $CXX -$STD..."
"$CXX" -E -P -std="$STD" -I"$CPP_DIR" "$TMP_TU" -o "$AST_DIR/preprocessed.cpp"

echo "[ast] dumping AST to JSON..."
"$CXX" -Xclang -ast-dump=json -fsyntax-only -std="$STD" -I"$CPP_DIR" "$TMP_TU" \
    > "$AST_DIR/ast.json" 2> "$AST_DIR/_ast.err" || {
    echo "warn: ast-dump reported errors (often harmless — see $AST_DIR/_ast.err)" >&2
    head -20 "$AST_DIR/_ast.err" || true
}

# Keep the error log next to ast.json for debugging.
rm -f "$TMP_TU"

echo "[ast] done: $AST_DIR/preprocessed.cpp + $AST_DIR/ast.json"
