use crate::ValueType;
use alloc::boxed::Box;
use core::marker::PhantomData;
use core::mem::{self, ManuallyDrop};

/// Internal tag bits stored in the high bits of `level` to discriminate
/// value/ref/mut-ref without relying on cross-crate pointer comparison of
/// const method tables. Conceptually `level` represents pointer depth only;
/// these tags are an implementation detail.
const VALUE_BIT: usize = 1 << (usize::BITS - 1);
const MUT_PTR_BIT: usize = 1 << (usize::BITS - 2);
const TAG_BITS: usize = VALUE_BIT | MUT_PTR_BIT;
const LEVEL_MASK: usize = !TAG_BITS;

/// Type alias: given a MethodsType `M`, yields an AbiClass parameterized by its Class.
pub type AbiOf<T> = AbiClass<<T as MethodsType>::Class>;

/// 跨语言调用的数据必须是具有'static生命周期，如果没有也需要Box包装后才能传递.
pub trait ClassType: ValueType + 'static {
    type Methods: MethodsType<Class = Self> + 'static;
}

/// Trait for the Methods struct generated by `export_class`.
/// Provides access to the Class type and the method tables.
pub trait MethodsType: 'static + Sized {
    type Class: ClassType;
    const METHODS: &'static AbiMethods<Self::Class>;
    const REF_METHODS: &'static AbiRefMethods<Self::Class>;
    const REF_MUT_METHODS: &'static AbiRefMutMethods<Self::Class>;
}

pub struct AbiRefMethods<T: ClassType>(AbiMethods<T>);
pub struct AbiRefMutMethods<T: ClassType>(AbiMethods<T>);

#[repr(C)]
pub struct BaseMethods<T: ClassType> {
    pub hicc_destroy: unsafe extern "C" fn(AbiClass<T>),
    pub hicc_make_unique: unsafe extern "C" fn(AbiClass<T>) -> AbiClass<T>,
    pub hicc_make_ref_mut: unsafe extern "C" fn(&mut AbiClass<T>) -> AbiClass<T>,
    pub hicc_size_of: unsafe extern "C" fn() -> usize,
    pub hicc_write: unsafe extern "C" fn(&mut AbiClass<T>, AbiClass<T>),
    pub hicc_make_ref: unsafe extern "C" fn(&AbiClass<T>) -> AbiClass<T>,
}

#[repr(C)]
pub struct AbiMethods<T: ClassType> {
    pub base: BaseMethods<T>,
    pub methods: T::Methods,
}

#[repr(C)]
pub struct AbiClass<T: ClassType> {
    pub methods: &'static AbiMethods<T>,
    pub this: *const (),
    pub level: usize,
    _mark: PhantomData<T>,
}

impl<T> Drop for AbiClass<T>
where
    T: ClassType,
{
    fn drop(&mut self) {
        unsafe {
            (self.methods.base.hicc_destroy)(Self { ..*self });
        }
    }
}

impl<T> AbiClass<T>
where
    T: ClassType,
{
    const fn base_methods() -> BaseMethods<T> {
        BaseMethods::<T> {
            hicc_destroy: Self::abi_destroy_boxed,
            hicc_make_unique: Self::abi_make_unique,
            hicc_make_ref_mut: Self::abi_make_ref_mut,
            hicc_size_of: Self::abi_size_of,
            hicc_write: Self::abi_write,
            hicc_make_ref: Self::abi_make_ref,
        }
    }

    const fn ref_methods() -> BaseMethods<T> {
        BaseMethods::<T> {
            hicc_destroy: Self::abi_destroy_ref,
            ..Self::base_methods()
        }
    }

    const fn ref_mut_methods() -> BaseMethods<T> {
        BaseMethods::<T> {
            hicc_destroy: Self::abi_destroy_ref_mut,
            ..Self::base_methods()
        }
    }

    pub const fn new_methods(methods: T::Methods) -> AbiMethods<T> {
        AbiMethods::<T> {
            base: Self::base_methods(),
            methods,
        }
    }

    pub const fn new_ref_methods(methods: T::Methods) -> AbiRefMethods<T> {
        AbiRefMethods(AbiMethods::<T> {
            base: Self::ref_methods(),
            methods,
        })
    }

    pub const fn new_ref_mut_methods(methods: T::Methods) -> AbiRefMutMethods<T> {
        AbiRefMutMethods(AbiMethods::<T> {
            base: Self::ref_mut_methods(),
            methods,
        })
    }

    unsafe extern "C" fn abi_destroy_boxed(self) {
        let obj = ManuallyDrop::new(self);
        let _ = unsafe { Box::from_raw(obj.this.cast::<T>().cast_mut()) };
    }
    // abi_destroy_ref/abi_destroy_ref_mut
    // 内部现需要利用这两个常量区分只读指针还是可写指针.
    unsafe extern "C" fn abi_destroy_ref(self) {
        mem::forget(self);
    }
    unsafe extern "C" fn abi_destroy_ref_mut(self) {
        mem::forget(self);
    }
    unsafe extern "C" fn abi_make_unique(mut self) -> Self {
        if self.actual_level() == 0 {
            self.methods = T::Methods::METHODS;
            self.level = VALUE_BIT | (self.level & LEVEL_MASK);
        }
        self
    }
    unsafe extern "C" fn abi_make_ref_mut(&mut self) -> Self {
        Self {
            methods: if self.is_mut() {
                &T::Methods::REF_MUT_METHODS.0
            } else {
                &T::Methods::REF_METHODS.0
            },
            level: self.level | MUT_PTR_BIT,
            ..*self
        }
    }
    unsafe extern "C" fn abi_make_ref(&self) -> Self {
        Self {
            methods: &T::Methods::REF_METHODS.0,
            level: self.level & !MUT_PTR_BIT,
            ..*self
        }
    }
    unsafe extern "C" fn abi_size_of() -> usize {
        mem::size_of::<T>()
    }
    unsafe extern "C" fn abi_write(&mut self, value: Self) {
        if self.is_mut() && self.actual_level() == 0 && value.actual_level() == 0 {
            let this = self.this.cast::<T>().cast_mut();
            unsafe { this.write(*value.take_boxed()) }
        }
    }
}

impl<T> AbiClass<T>
where
    T: ClassType,
{
    pub fn with_boxed(obj: Box<T>) -> Self {
        let this = Box::into_raw(obj).cast();
        Self {
            methods: T::Methods::METHODS,
            this,
            level: VALUE_BIT,
            _mark: PhantomData,
        }
    }
    pub fn with_ptr(this: *const (), level: usize) -> Self {
        Self {
            methods: &T::Methods::REF_METHODS.0,
            this: this.cast_mut(),
            level,
            _mark: PhantomData,
        }
    }

    pub fn with_mut_ptr(this: *mut (), level: usize) -> Self {
        Self {
            methods: &T::Methods::REF_MUT_METHODS.0,
            this,
            level: level | MUT_PTR_BIT,
            _mark: PhantomData,
        }
    }

    pub fn this_mut_ptr(&self, level: usize) -> *mut () {
        if self.is_mut() {
            return self.this_ptr(level).cast_mut();
        }
        panic!("not mut pointer");
    }

    pub fn this_ptr(&self, level: usize) -> *const () {
        let actual = self.actual_level();
        if level > actual {
            panic!(
                "expect {}-level pointer, but is {}-level pointer",
                level + 1,
                actual + 1
            );
        }
        let mut this = self.this as *mut *mut ();
        for _ in level..actual {
            this = unsafe { (*this).cast() };
        }
        this.cast()
    }

    pub fn take_boxed(self) -> Box<T> {
        if self.is_value() {
            assert_eq!(self.actual_level(), 0);
            let this = ManuallyDrop::new(self);
            return unsafe { Box::from_raw(this.this_ptr(0).cast::<T>().cast_mut()) };
        }
        panic!("not Box<T>");
    }

    /// Extract the actual pointer-indirection level (pointer depth), masking out internal tag bits.
    fn actual_level(&self) -> usize {
        self.level & LEVEL_MASK
    }

    pub fn is_value(&self) -> bool {
        self.level & VALUE_BIT != 0
    }
    pub fn is_pointer(&self) -> bool {
        !self.is_value()
    }
    pub fn is_const(&self) -> bool {
        !self.is_value() && (self.level & MUT_PTR_BIT) == 0
    }
    pub fn is_mut(&self) -> bool {
        !self.is_const()
    }
}
