# cython: language_level=3
"""
Cython test for the example-basic_lib Rust crate.

Includes hicc_demo.pxd (auto-generated by hicc-cbindgen -l cython)
for C-level type definitions at compile time.

Functionally equivalent to c/main.c — exercises all FFI types:
  - Plain POD types (i32, Point)
  - Owned heap types (AbiClass with explicit destroy)
  - Pass-by-value ownership transfer to Rust
"""
include "hicc_demo.pxd"


def main():
    cdef const Hicc_demo *fn = demo()

    # 1. Plain i32 — no allocation, no destroy needed
    cdef int32_t sum = fn.add(3, 4)
    print(f"add(3, 4) = {sum}")
    assert sum == 7

    cdef int32_t neg = fn.negate(5)
    print(f"negate(5) = {neg}")
    assert neg == -5

    # 2. Container<i32> — owned heap value, explicit destroy
    cdef AbiClass_Container_i32 c = fn.new_container(42)
    cdef int32_t val = c.methods.get(&c)[0]
    print(f"container_value(42) = {val}")
    assert val == 42
    c.methods.hicc_destroy(c)

    # 3. Option<i32> — owned heap value, explicit destroy
    cdef AbiClass_Option_i32 opt = fn.new_option(99)
    cdef int64_t doubled = opt.methods.as_ref(&opt)[0] * 2
    print(f"double_option(Some(99)) = {doubled}")
    assert doubled == 198
    opt.methods.hicc_destroy(opt)

    # 4. Str — heap-allocated, explicit destroy
    cdef AbiClass_Ref_str s = fn.new_str()
    cdef uintptr_t length = s.methods.len(&s)
    print(f"check_str(\"hello\") = {length}")
    assert length == 5
    s.methods.hicc_destroy(s)

    # 5. Slice<Option<i32>> — pass by value transfers ownership to Rust
    cdef AbiClass_Ref_Slice_Option_i32 slice_val = fn.new_slice()
    cdef uintptr_t count = fn.count_some(slice_val)
    print(f"count_some(&[Some(10), None, Some(30)]) = {count}")
    assert count == 2

    # 6. Array<&'static str, 3> — pass by value transfers ownership to Rust
    cdef AbiClass_Array_Ref_str arr = fn.new_array()
    cdef uintptr_t total = fn.total_len(arr)
    print(f"total_len([\"a\", \"bb\", \"ccc\"]) = {total}")
    assert total == 6

    # 7. Point (POD struct) — no allocation, no destroy needed
    cdef Point p1
    p1.x = 10
    p1.y = 20
    cdef Point p2
    p2.x = 1
    p2.y = 2
    cdef Point sum_pt = fn.add_point(p1, p2)
    print(f"add_point((10,20), (1,2)) = ({sum_pt.x}, {sum_pt.y})")
    assert sum_pt.x == 11
    assert sum_pt.y == 22

    print("Basic lib example passed!")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
