# cython: language_level=3
"""
Cython test for the example-foreign_type Rust crate.

Includes hicc_foreign_type.pxd (auto-generated by hicc-cbindgen -l cython)
for C-level type definitions at compile time.

Functionally equivalent to c/main.c — exercises all FFI types:
  - AbiClass_Ref_str (&str — built-in type)
  - AbiClass_ForeignType_String (String — foreign type)
  - AbiClass_ForeignType_Vec_String (Vec<String> — foreign type)
  - Owned heap types (AbiClass with explicit hicc_destroy)
  - Pass-by-value ownership transfer to Rust
"""
include "hicc_foreign_type.pxd"


def main():
    cdef const Hicc_foreign_type *fn = foreign_type()

    print("=== Lib entry ===")

    # ===== str methods (AbiClass_Ref_str — built-in hicc type) =====
    print("\n--- str methods ---")
    cdef AbiClass_Ref_str s = fn.new_str()

    cdef uintptr_t s_len = s.methods.len(&s)
    print("s.len() =", s_len, "(expect 5)")
    assert s_len == 5

    cdef uintptr_t s_size = s.methods.hicc_size_of()
    print("s.size_of() =", s_size)

    cdef uint8_t first = s.methods.get(&s, 0)
    print("s.get(0) =", chr(first), "(expect 'h')")
    assert first == ord('h')

    cdef AbiClass_Ref_str s_ref = s.methods.hicc_make_ref(&s)
    cdef uintptr_t s_ref_len = s_ref.methods.len(&s_ref)
    print("s_ref.len() =", s_ref_len, "(expect 5)")
    assert s_ref_len == 5

    cdef AbiClass_Ref_str s_mut = s.methods.hicc_make_ref_mut(&s)
    cdef uintptr_t s_mut_len = s_mut.methods.len(&s_mut)
    print("s_mut.len() =", s_mut_len, "(expect 5)")
    assert s_mut_len == 5

    cdef AbiClass_Ref_str s_owned = s.methods.hicc_make_unique(s)
    cdef uintptr_t s_owned_len = s_owned.methods.len(&s_owned)
    print("s_owned.len() =", s_owned_len, "(expect 5)")
    assert s_owned_len == 5
    s_owned.methods.hicc_destroy(s_owned)
    # make_unique consumed s; get a fresh one
    s = fn.new_str()

    # ===== Vec methods =====
    print("\n--- Vec methods ---")
    cdef AbiClass_ForeignType_Vec_String v = fn.new_vec_string()

    cdef uintptr_t v_size = v.methods.hicc_size_of()
    print("v.size_of() =", v_size)

    cdef uintptr_t v_len = v.methods.len(&v)
    print("v.len() before push =", v_len, "(expect 0)")
    assert v_len == 0

    cdef AbiClass_ForeignType_Vec_String v_ref = v.methods.hicc_make_ref(&v)
    cdef uintptr_t v_ref_len = v_ref.methods.len(&v_ref)
    print("v_ref.len() =", v_ref_len, "(expect 0)")
    assert v_ref_len == 0

    cdef AbiClass_ForeignType_Vec_String v_mut = v.methods.hicc_make_ref_mut(&v)
    cdef uintptr_t v_mut_len = v_mut.methods.len(&v_mut)
    print("v_mut.len() =", v_mut_len, "(expect 0)")
    assert v_mut_len == 0

    # ===== Lib push =====
    print("\n--- push ---")
    cdef AbiClass_ForeignType_String result = fn.push(&v, s)
    print("fn.push(&v, s) -> result")

    v_len = v.methods.len(&v)
    print("v.len() after push =", v_len, "(expect 1)")
    assert v_len == 1

    # ===== String methods =====
    print("\n--- String methods ---")

    cdef uintptr_t result_size = result.methods.hicc_size_of()
    print("result.size_of() =", result_size)

    cdef uintptr_t result_len = result.methods.len(&result)
    print("result.len() =", result_len, "(expect 5)")
    assert result_len == 5

    cdef AbiClass_Ref_str result_str = result.methods.as_str(&result)
    cdef uintptr_t result_str_len = result_str.methods.len(&result_str)
    print("result.as_str().len() =", result_str_len, "(expect 5)")
    assert result_str_len == 5
    cdef uint8_t result_first = result_str.methods.get(&result_str, 0)
    print("result.as_str()[0] =", chr(result_first), "(expect 'h')")
    assert result_first == ord('h')

    # push_str: value-passed &str arg is consumed by Rust side
    cdef AbiClass_Ref_str s2 = fn.new_str()
    result.methods.push_str(&result, s2)
    result_len = result.methods.len(&result)
    print("result.len() after push_str =", result_len, "(expect 10)")
    assert result_len == 10

    cdef AbiClass_ForeignType_String result_ref = result.methods.hicc_make_ref(&result)
    cdef uintptr_t result_ref_len = result_ref.methods.len(&result_ref)
    print("result_ref.len() =", result_ref_len, "(expect 10)")
    assert result_ref_len == 10

    cdef AbiClass_ForeignType_String result_owned = result.methods.hicc_make_unique(result)
    cdef uintptr_t result_owned_len = result_owned.methods.len(&result_owned)
    print("result_owned.len() =", result_owned_len, "(expect 10)")
    assert result_owned_len == 10
    result_owned.methods.hicc_destroy(result_owned)
    # s2 consumed by push_str; get fresh
    s2 = fn.new_str()
    # result consumed by make_unique; get fresh
    result = fn.push(&v, s2)

    # ===== Write: overwrite v with a fresh vec =====
    print("\n--- Write ---")
    cdef AbiClass_ForeignType_Vec_String v_fresh = fn.new_vec_string()
    cdef AbiClass_Ref_str s3 = fn.new_str()
    cdef AbiClass_ForeignType_String r3 = fn.push(&v_fresh, s3)
    v.methods.hicc_write(&v, v_fresh)
    v_len = v.methods.len(&v)
    print("v.len() after write =", v_len, "(expect 1)")
    assert v_len == 1
    r3.methods.hicc_destroy(r3)

    # ===== Vec.push via method table =====
    print("\n--- Vec.push via methods ---")
    cdef AbiClass_Ref_str s4 = fn.new_str()
    cdef AbiClass_ForeignType_String s4_string = fn.push(&v, s4)
    v_len = v.methods.len(&v)
    print("v.len() after fn->push =", v_len, "(expect 2)")
    assert v_len == 2

    # Push s4_string again via method table — value-passed AbiClass arg
    v.methods.push(&v, s4_string)
    v_len = v.methods.len(&v)
    print("v.len() after methods->push =", v_len, "(expect 3)")
    assert v_len == 3

    # ===== Final cleanup =====
    print("\n--- cleanup ---")
    result.methods.hicc_destroy(result)
    v.methods.hicc_destroy(v)

    print("\nForeign type example passed!")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())